SELECT COUNT(*) FROM [TRS_Underwriting_Deals] 
LEFT JOIN [dbo].[TRS_Underwriting_DeclineReasons] AS [MainDecline] ON [TRS_Underwriting_Deals].[DeclineReason] = [MainDecline].[NumericID]
LEFT JOIN [dbo].[TRS_Underwriting_DeclineReasons] AS [SubDecline] ON [TRS_Underwriting_Deals].[SubDeclineReasonID] = [SubDecline].[NumericID]
LEFT JOIN [dbo].[TRS_Underwriting_UWDealStatuses] AS [CurrentUWDealStatus] ON [TRS_Underwriting_Deals].[UWDealStatus] = [CurrentUWDealStatus].[NumericID]
LEFT JOIN [dbo].[TRS_Underwriting_UWDealStatuses] AS [PriorUWDealStatus] ON [TRS_Underwriting_Deals].[PriorUWDealStatus] = [PriorUWDealStatus].[NumericID]
LEFT JOIN [dbo].[TRS_Lists_FundingCompetitors] AS [FundCompet] ON [TRS_Underwriting_Deals].[FundingBehindFundingCompetitorID] = [FundCompet].[NumericID]
LEFT JOIN [dbo].[TRS_Lists_FundingCompetitors] AS [MerchTook] ON [TRS_Underwriting_Deals].[MerchantTookFundsFromFundingCompetitorID] = [MerchTook].[NumericID]
LEFT JOIN [dbo].[TRS_Lists_AdvancePurposes] ON [TRS_Underwriting_Deals].[AdvancePurposeID] = [TRS_Lists_AdvancePurposes].[NumericID]
LEFT JOIN [dbo].[TRS_Merchants] ON [TRS_Underwriting_Deals].[MerchantID] = [TRS_Merchants].[NumericID]
LEFT JOIN [dbo].[TRS_BusinessPersons] AS [PO] ON [TRS_Merchants].[PrimaryOwnerID] = [PO].[NumericID]
LEFT JOIN [dbo].[TRS_BusinessPersons] AS [SO] ON [TRS_Merchants].[SecondaryOwnerID] = [SO].[NumericID]
LEFT JOIN [dbo].[TRS_BusinessPersons] AS [TO] ON [TRS_Merchants].[ThirdOwnerID] = [TO].[NumericID]
LEFT JOIN [dbo].[TRS_BusinessPersons] AS [FO] ON [TRS_Merchants].[FourthOwnerID] = [FO].[NumericID]
LEFT JOIN [dbo].[TRS_Deals] ON [TRS_Underwriting_Deals].[DealID] = [TRS_Deals].[NumericID]
LEFT JOIN [dbo].[TRS_Site_BrandedCompanies] ON [TRS_Deals].[BrandedCompanyID] = [TRS_Site_BrandedCompanies].[NumericID]
LEFT JOIN [dbo].[Security_Users] AS [Underwriter] ON [TRS_Deals].[UnderwriterID] = [Underwriter].[NumericID]
LEFT JOIN [dbo].[Security_Users] AS [CreditAnalyst] ON [TRS_Deals].[CreditAnalystID] = [CreditAnalyst].[NumericID]
LEFT JOIN [dbo].[TRS_SalesRepresentatives] AS [SalesRep] ON [TRS_Deals].[SalesRepresentativeID] = [SalesRep].[NumericID]
LEFT JOIN [dbo].[TRS_SalesRepresentatives] AS [ParentISO] ON [SalesRep].[ParentISOID] = [ParentISO].[NumericID]
  WHERE  (([TRS_Underwriting_Deals].[UWDealStatus] < 201) AND ([TRS_Underwriting_Deals].[UWDealStatus] >= -8) AND ([TRS_Underwriting_Deals].[MerchantID] = 370768)) 